#!/bin/bash

logToMediaMessages() {
    currTime=$(LANG=C date "+%b %d %H:%M:%S localhost")
    echo "$currTime BackupRecover[9999]: $1" >> /media/messages
}

sd=`mount  | grep "mnt" | cut -b 6-8`

parts="${sd}1 ${sd}2 ${sd}8"

# mount log partition.
mount /dev/${sd}5 /media

#logToMediaMessages "uefi mode, backup init image start."
ocs-sr -q2 -j2 -z1p -i 2000 --nogui -p true saveparts init-image $parts
rc=$?

if [ $rc -ne 0 ]
then
    logToMediaMessages "uefi mode, backup init image failed, error code: $rc."
else
    logToMediaMessages "uefi mode, backup init image success."
fi
exit $rc

