#!/bin/bash

logToMediaMessages() {
    currTime=$(LANG=C date "+%b %d %H:%M:%S localhost")
    echo "$currTime BackupRecover[9999]: $1" >> /media/messages
}

sd=`mount  | grep "mnt" | cut -b 6-8`

parts="${sd}1 ${sd}2 ${sd}8" 

mount /dev/${sd}5 /media

if [ $# -gt 0 ]
then
    image=$1
else
    image="recent-image"
fi

#logToMediaMessages "uefi mode, recover from recent image start."

ocs-sr -q2 -j2 -k --nogui -z1p -i 2000 -p true restoreparts $image $parts
rc=$?

if [ $rc -ne 0 ]
then
    logToMediaMessages "uefi mode, recover from recent image $image failed, error code: $rc."
else
    logToMediaMessages "uefi mode, recover from recent image $image success."
fi
exit $rc

